---
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
serviceTCP:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-sv
  type: LoadBalancer
  loadBalancerIP: 192.168.1.50
serviceUDP:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-sv
  type: LoadBalancer
  loadBalancerIP: 192.168.1.50
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
# If using in the real world, set up admin.existingSecret instead.
adminPassword: admin