apiVersion: v1
kind: Service
metadata:
  name: jupyter
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - port: 8888
    name: web
    targetPort: 8888
  selector:
    app: jupyter
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-deployment
  labels:
    app: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: jupyter
        image:  lukasball/my-jupyter-container:0.6
        ports:
        - containerPort: 8888
        env:
        - name: git_repo
          value: git@github.com:lukasb27/my-jupyter-notebooks.git
        volumeMounts:
        - name: my-ssh-key
          mountPath: "/var/my-app-secrets"
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - cp /var/my-app-secrets/id_rsa ~/.ssh/id_rsa; chmod 600 ~/.ssh/id_rsa
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
      - name: my-ssh-key
        secret:
          secretName: my-ssh-key
