apiVersion: v1
kind: Service
metadata:
  name: jenkins
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - port: 8080
    name: web
    targetPort: 8080
  - port: 50000
    targetPort: 50000
    name: agent
  selector:
    app: jenkins
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins4eval/jenkins:slim-arm
        ports:
        - containerPort: 8080
        - containerPort: 50000
      nodeSelector:
        worker: pi
