apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
type: Opaque
stringData:
  INFLUXDB_CONFIG_PATH: /etc/influxdb/influxdb.conf
  INFLUXDB_ADMIN_USER: lukas
  INFLUXDB_ADMIN_PASSWORD: password
  INFLUXDB_DB: grafana
  INFLUXDB_USER: lukas
  INFLUXDB_USER_PASSWORD: password